### PR TITLE
Add canvas todo structs for use in users/self/todo

### PR DESCRIPTION
**Pull request by reverse**
I added the structs needed to convert the serde hashmap to a legitimate struct. I also moved the /users/self/todo method off of the development feature. I have included a test for the async todo list. I had a switch a few fields around in assignment, but I haven't seen any compatibility issues.

### CODE REVIEW

**Comment by thvdveld** [comment]
Thank you! It looks good to me! (Just adding some minor stuff in #2).

**Comment by reverse** [comment]
Great, thank you very much! This package was extremely helpful for me. 

Are you planning on pushing this version to crates.io / is that automated?

**Comment by thvdveld** [comment]
It is not automated since it is still very work in progress (though I'm not actively adding features). We use it at our university for automating things. I only added the features that we needed. I'm glad that it was helpful for you! I'll push a new version.

**Comment by thvdveld** [comment]
Pushed a new version for you! 😉

**Comment by reverse** [comment]
Thank you! Although, I'm not seeing the TODO method on the non-devel branch with version 0.4.2. What about you?

Thanks for all of the help pushing and merging again.

**Comment by thvdveld** [comment]
I did an oopsie. I think it is fixed now (published 0.5.0).

**Comment by reverse** [comment]
Great, that fixed it for me. Thanks for all of the help! Have a great rest of your day/night.

**Pull request merged**
